version: '3.8'
services:
  payment_service:
    build: .
    container_name: payment_service
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROBOKASSA_LOGIN=${ROBOKASSA_LOGIN}
      - ROBOKASSA_PASSWORD1=${ROBOKASSA_PASSWORD1}
      - ROBOKASSA_PASSWORD2=${ROBOKASSA_PASSWORD2}
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on: []

